### ISSUE TITLE
Issues with latest client

### ISSUE THREAD

**Issue by Dextan** [Temperament/Estrella#1]
(Exception) Error loading dataprovider: System.OverflowException: Der Wert für einen UInt16 war zu groß oder zu klein.
   bei System.Convert.ToUInt16(UInt32 value)
   bei System.UInt32.System.IConvertible.ToUInt16(IFormatProvider provider)
   bei System.Convert.ToUInt16(Object value)
   bei Zepheus.Database.DataStore.GetDataTypes.GetUshort(Object Row) in C:\Users\Administrator\Desktop\Estrella Test\Estrella New\Estrella\Zepheus.Database\DataStore\GetDataTypes.cs:Zeile 24.
   bei Zepheus.FiestaLib.Data.ActiveSkillInfo.Load(DataRow row) in C:\Users\Administrator\Desktop\Estrella Test\Estrella New\Estrella\Zepheus.FiestaLib\Data\ActiveSkillInfo.cs:Zeile 47.
   bei Zepheus.Zone.Data.DataProvider.LoadActiveSkills() in C:\Users\Administrator\Desktop\Estrella Test\Estrella New\Estrella\Zepheus.Zone\Data\DataProvider.cs:Zeile 268.
   bei Zepheus.Zone.Data.DataProvider..ctor() in C:\Users\Administrator\Desktop\Estrella Test\Estrella New\Estrella\Zepheus.Zone\Data\DataProvider.cs:Zeile 57.
   bei Zepheus.Zone.Data.DataProvider.Load() in C:\Users\Administrator\Desktop\Estrella Test\Estrella New\Estrella\Zepheus.Zone\Data\DataProvider.cs:Zeile 70.
[17.10.2015 21:10:32](Error) Server could not be started. Errors o

and with latest client 

(Warn) Invalid client authentication from

where is the problem

**Comment by Temperament** [comment]
https://github.com/Temperament/Estrella/commit/39913ad1026703d8cdd551e5a94ecdf7eeb3b443 - should fix the issue.
